import 'dart:math';

class QuoteGenerator {
  static final Random _random = Random();

  static const List<String> _quotes = [
    // Motivation (25 quotes)
    "You are stronger than you know!",
    "Keep pushing forward, one step at a time.",
    "Every challenge is a chance to grow.",
    "Your effort today shapes your tomorrow.",
    "Believe in yourself, and anything is possible.",
    "The only limit is the one you set.",
    "Rise above doubts and soar to new heights.",
    "Small actions lead to big results.",
    "Stay determined, and you’ll find a way.",
    "Your dreams are worth the fight.",
    "Turn obstacles into opportunities.",
    "Keep going, even when it’s tough.",
    "You have the power to change your story.",
    "Embrace the journey, not just the destination.",
    "Courage is taking one more step.",
    "Your persistence will pay off.",
    "Every day is a fresh start to chase your goals.",
    "Don’t wait for perfect—start now.",
    "You’re capable of amazing things.",
    "Let your passion fuel your progress.",
    "The harder you work, the closer you get.",
    "Mistakes are lessons in disguise.",
    "Your potential is limitless.",
    "Stay focused and keep moving forward.",
    "You’re one decision away from a new path.",

    // Happiness (25 quotes)
    "Happiness is found in the present moment.",
    "Smile, it’s a brand-new day!",
    "Joy comes from within—let it shine!",
    "Find beauty in the little things.",
    "Spread kindness, and feel the warmth return.",
    "A happy heart makes everything brighter.",
    "Choose joy, even on cloudy days.",
    "Laughter is the best medicine.",
    "Savor the simple pleasures in life.",
    "Your smile can light up the world.",
    "Happiness grows when you share it.",
    "Dance like nobody’s watching!",
    "Every sunrise brings new possibilities.",
    "Find peace in the moment you’re in.",
    "Let go of worries and embrace today.",
    "A kind word can spark a joyful day.",
    "Happiness is a choice—make it yours.",
    "Surround yourself with what lifts you up.",
    "Celebrate the small victories.",
    "Joy is contagious—spread it freely.",
    "Breathe deeply and feel the calm.",
    "Life’s beauty is in its fleeting moments.",
    "A cheerful heart finds joy everywhere.",
    "Be your own sunshine on rainy days.",
    "Happiness blooms where love is planted.",

    // Success (25 quotes)
    "Success is built one step at a time.",
    "Your dreams are closer than you think.",
    "Hard work turns possibilities into realities.",
    "Every small win counts toward greatness.",
    "Stay focused, and you’ll reach your goals.",
    "The path to success is paved with effort.",
    "Believe in your vision, and make it happen.",
    "Opportunities come to those who act.",
    "Your dedication will open doors.",
    "Success is the reward of persistence.",
    "Dream big, work hard, stay humble.",
    "Every goal starts with a single choice.",
    "You’re building your future today.",
    "Stay patient, but never stop moving.",
    "Great things come from consistent effort.",
    "Your hard work will tell your story.",
    "Success is earned, not given.",
    "Take risks to unlock your potential.",
    "Progress is better than perfection.",
    "Your focus determines your reality.",
    "Keep climbing, the view is worth it.",
    "Small steps today lead to big wins tomorrow.",
    "You’re writing your own success story.",
    "Stay disciplined, and success will follow.",
    "The journey to success is your greatest teacher.",

    // Gratitude (25 quotes)
    "Gratitude turns what you have into enough.",
    "Be thankful for the little moments that matter.",
    "Appreciate today, and tomorrow will glow.",
    "A grateful heart attracts more blessings.",
    "Give thanks, and watch positivity grow.",
    "Every day is a gift—cherish it.",
    "Gratitude transforms your perspective.",
    "Say thank you, and feel the joy.",
    "Appreciation makes every moment richer.",
    "Be grateful for the journey, not just the destination.",
    "A thankful mind finds peace.",
    "Count your blessings, not your burdens.",
    "Gratitude is the key to contentment.",
    "Thankfulness creates a ripple of kindness.",
    "See the good, and it multiplies.",
    "A grateful heart is a happy heart.",
    "Give thanks for both the big and small.",
    "Gratitude makes every day brighter.",
    "Appreciate the people who lift you up.",
    "Be thankful for where you are right now.",
    "Gratitude is the foundation of joy.",
    "Every moment is a chance to be thankful.",
    "A thankful attitude changes everything.",
    "Give thanks, and life feels fuller.",
    "Gratitude is the spark that lights up life.",
    "You are stronger than you know!",
    "Keep pushing forward, one step at a time.",
    "Every challenge is a chance to grow.",
    "Your effort today shapes your tomorrow.",
    "Believe in yourself, and anything is possible.",
    "Happiness is found in the present moment.",
    "Smile, it’s a brand-new day!",
    "Joy comes from within—let it shine!",
    "Find beauty in the little things.",
    "Spread kindness, and feel the warmth return.",
    "Success is built one step at a time.",
    "Your dreams are closer than you think.",
    "Hard work turns possibilities into realities.",
    "Every small win counts toward greatness.",
    "Stay focused, and you’ll reach your goals.",
    "Gratitude turns what you have into enough.",
    "Be thankful for the little moments that matter.",
    "Appreciate today, and tomorrow will glow.",
    "A grateful heart attracts more blessings.",
    "Give thanks, and watch positivity grow.",
    "Seize the day with unstoppable energy!",
    "Your passion fuels your success!",
    "Rise up and make today amazing!",
    "You’ve got the power to change the world!",
    "Let your enthusiasm light the way!",
    "Every moment is a fresh start!",
    "Turn obstacles into opportunities!",
    "Your courage inspires others!",
    "Embrace the journey with a bold heart!",
    "Shine bright, the world needs your light!",
    "Take action now—your future is waiting!",
    "You are unstoppable when you believe!",
    "Make every second count today!",
    "Your energy is contagious—spread it!",
    "Dream big, then chase it with all you’ve got!",
    "Today is your day to soar!",
    "Let positivity guide your every step!",
    "You’re one choice away from greatness!",
    "Fuel your day with purpose and passion!",
    "The best is yet to come—go get it!",
    "Your smile can change someone’s day!",
    "Leap into action with fearless spirit!",
    "You’re capable of incredible things!",
    "Make today a masterpiece of joy!",
    "Your determination moves mountains!",
    "Live boldly, love fiercely, act now!",
    "Every effort brings you closer to victory!",
    "Radiate positivity and watch magic happen!",
    "You’re the spark that ignites progress!",
    "Chase your goals with relentless drive!",
    "Today’s actions create tomorrow’s triumphs!",
    "Your potential is limitless—unleash it!",
    "Be the energy you want to attract!",
    "Conquer your fears with a fearless heart!",
    "Make today vibrant with your unique spark!",
    "Your journey is yours to shape—start now!",
    "Embrace challenges as stepping stones!",
    "You’re a force of nature—keep moving!",
    "Let your dreams fuel your daily grind!",
    "Turn your vision into reality today!",
    "Your positivity transforms the ordinary!",
    "Take the lead and inspire the world!",
    "Every day is a chance to shine brighter!",
    "You’re built for greatness—go prove it!",
    "Act with purpose, live with passion!",
    "Your heart knows the way—follow it!",
    "Make waves with your boundless energy!",
    "Today is yours to conquer—go for it!",
    "You’re a beacon of hope and action!",
    "Push past limits and redefine possible!",
    "Your hustle today builds your legacy!",
    "Live vibrantly, love wholeheartedly!",
    "You’re one step from a breakthrough!",
    "Ignite your day with fearless ambition!",
    "Your spirit is unstoppable—keep going!",
    "Create joy in every moment you live!",
    "You’re destined for extraordinary things!",
    "Turn your dreams into today’s reality!",
    "Your energy shapes the world around you!",
    "Be bold, be brave, be unstoppable!",
    "Every action you take builds your future!",
    "You’re a powerhouse of potential!",
    "Make today count with every heartbeat!",
    "Your enthusiasm turns dreams to reality!",
    "Leap forward with courage and conviction!",
    "You’re the architect of your success!",
    "Live each moment with vibrant purpose!",
    "Your drive inspires everyone around you!",
    "Seize every opportunity today brings!",
    "You’re a spark of brilliance—shine on!",
    "Transform today with your bold actions!",
    "Your passion creates endless possibilities!",
    "Be the change you want to see today!",
    "You’re unstoppable when you’re inspired!",
    "Make every moment burst with energy!",
    "Your journey to greatness starts now!",
    "Live today like it’s your masterpiece!",
    "Charge into today with boundless enthusiasm!",
    "Your courage lights up the world!",
    "Make today unforgettable with your energy!",
    "Embrace {action} and {benefit}!",
    "You are {positiveTrait}—{action}!",
    "Today is your {opportunity}—{action}!",
    "Let your {positiveTrait} {action}!",
    "Transform today with your {positiveTrait}!",
    "Your {positiveTrait} creates {benefit}!",
    "{Action} with {positiveTrait} and {benefit}!",
    "Be {positiveTrait} and {action} today!",
    "Your {action} fuels your {benefit}!",
    "Seize {opportunity} with {positiveTrait}!",
    "courage",
    "effort",
    "passion",
    "focus",
    "kindness",
    "energy",
    "drive",
    "boldness",
    "creativity",
    "determination",
    "action",
    "resilience",
    "enthusiasm",
    "commitment",
    "inspiration",
    "conquer your fears",
    "achieve your dreams",
    "inspire others",
    "create possibilities",
    "shine brightly",
    "build your future",
    "spark joy",
    "move mountains",
    "reach new heights",
    "make a difference",
    "transform your life",
    "ignite success",
    "unleash greatness",
    "shape your destiny",
    "spread positivity",
    "unstoppable",
    "brilliant",
    "fearless",
    "vibrant",
    "powerful",
    "radiant",
    "inspired",
    "resilient",
    "bold",
    "passionate",
    "determined",
    "joyful",
    "creative",
    "energetic",
    "courageous",
    "chance",
    "moment",
    "day",
    "opportunity",
    "time",
    "journey",
    "path",
    "adventure",
    "destiny",
    "future",
    "spark",
    "canvas",
    "stage",
    "calling",
    "legacy",
  ];

  static String getRandomQuote() {
    return _quotes[_random.nextInt(_quotes.length)];
  }
}
